# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    container_name: psql_database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
